### ISSUE TITLE
Not working for V2 Aadhaar secure QR

### ISSUE THREAD

**Issue by shashidharac** [tanmoysrt/pyaadhaar#11]
**Describe the bug**
In V2 Aadhaar secure QR few more fields are added, i'm trying in java currently able to retrieve the all the fields but facing some issue w.r.t photo saving. Can you throw some light how the photo data processed and saved ?

**Comment by Arkajit-Datta** [comment]
The new PR #10 actually solves this issue

**Comment by tanmoysrt** [comment]
After few changes, I am planning to release new version by tonight, Ig that will resolve all the issues

**Comment by tanmoysrt** [comment]
@shashidharac kindly update your pyaadhaar version to 2.0.2  https://pypi.org/project/pyaadhaar/ . The issues has been fixed.
Thanks @Arkajit-Datta for your valuable contribution

**Comment by Arkajit-Datta** [comment]
My pleasure @tanmoysrt
