### ISSUE TITLE
Minimal reproducible example

### ISSUE THREAD

**Issue by divine-architect** [tanmoysrt/pyaadhaar#12]
Hi, in the readme, it is specified <data got from qr>

what exactly does this mean?
is it in bytes or strings, if any of the two, how do i decode them? will any python library do or do is there a specific way to decode aadhar qrcodes?

**Comment by tanmoysrt** [comment]
Can you say a more detailed ?

**Comment by divine-architect** [comment]
How do I fetch the data from the qr code?

**Comment by tanmoysrt** [comment]
> How do I fetch the data from the qr code? should i use a python library like pyzbar?

You can use any qr read library to ready the string of characters from QR code and pass it to the constructor

Or check this https://github.com/tanmoysrt/pyaadhaar#-decode-image-of-qr-code-
There is already a file to read content of QR using opencv, you can use that also

**Comment by divine-architect** [comment]
ah thanks, my bad I didnt' read the docs properly!!
