### ISSUE TITLE
AadhaarSecureQr() fails with exception `string index out of range`

### ISSUE THREAD

**Issue by rahulc93** [tanmoysrt/pyaadhaar#8]
**Describe the bug**
Ran the example code on my Aadhaar QR code and AadhaarSecureQr() failed with an exception `string index out of range`.
<img width="207" alt="aadhar_qr_code" src="https://user-images.githubusercontent.com/2138560/199962368-d5bd753e-c301-4135-aa67-159d7820328d.png">

**To Reproduce**
Run the example code in README on the QR code image (attached).

**Expected behavior**
Aadhaar details should be extracted properly.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] iOS

**Additional context**

**Comment by rahulc93** [comment]
```python
#!/Users/rahulchowdhury/.virtualenvs/site_poc_env/bin/python

import os
import cv2
from pyaadhaar.decode import AadhaarSecureQr

from pyzbar.pyzbar import decode
from pyaadhaar.utils import isSecureQr, Qr_img_to_text


def main():
    image_file_name = "aadhar_qr_code.png"
    image_path = os.path.join(os.getcwd(), image_file_name)
    print(os.path.isfile(image_path))

    img = cv2.imread(image_path)
    print('imread')
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    print('cvtColor')

    code = decode(gray)
    qrData = code[0].data
    print('qrData')

    # qrData = Qr_img_to_text(image_path)[0]

    isSecureQR = isSecureQr(qrData)

    if isSecureQR:
        secure_qr = AadhaarSecureQr(int(qrData))
        print('AadhaarSecureQr')
        decoded_secure_qr_data = secure_qr.decodeddata()
        print('secure_qr.decodeddata')
        print(decoded_secure_qr_data)


if __name__ == "__main__":
    main()

```

This is the script I am using.


opencv-python==4.6.0.66
pyaadhaar==1.1.3
pyzbar==0.1.9

**Comment by Tanmoy741127** [comment]
OK, I will check this out!

**Comment by Arkajit-Datta** [comment]
Hey @Tanmoy741127. We should release a new update to the main branch now. I have a few more updates on the image extraction part. This issue should be resolved with what we have in the main branch

**Comment by Tanmoy741127** [comment]
Sure @Tanmoy741127 I will do that within 2 days

**Comment by Arkajit-Datta** [comment]
Ohhh no please wait for few of my PRs I was working on a few changes, will do that an then lets release an update.

**Comment by Tanmoy741127** [comment]
Ok fine

**Comment by shashankmuralidhar** [comment]
Hi, 

With the updated code for handling the QR data, we are unable to retrieve the image and signature which we could extract earlier. How do I extract the image now?
Help towards this will be very much appreciated.

Thanks in advance

**Comment by Tanmoy741127** [comment]
Wait for a few days, I will check the latest docs. Then will release a new
version.

**Comment by shashankmuralidhar** [comment]
Thanks a lot for the update.

**Comment by Arkajit-Datta** [comment]
So the problem what happened was that we updated the version - 2 details. But there was a static length to fetch the image. Which was previously 15, but it should be essentially dynamic with the length of details. As it'll help us to map the image properly everytime

**Comment by Arkajit-Datta** [comment]
I have also added a function called isImage() which will help us to find if we have an image present in the QR code, probably we can add that in our documentation as well.

**Comment by Arkajit-Datta** [comment]
Hey, @Tanmoy741127 I have opened a PR, please have a look. should mostly solve the issue.

**Comment by Tanmoy741127** [comment]
Ok Thanks

**Comment by Arkajit-Datta** [comment]
Also, it'll be great, @Tanmoy741127/ @rahulc93/ @shashankmuralidhar if you guys can test at your end. Then we can close this issue as well.

**Comment by Tanmoy741127** [comment]
Sure Arkajit will check the PR

**Comment by Arkajit-Datta** [comment]
@Tanmoy741127 @shashankmuralidhar no problem guys! ☺

**Comment by Arkajit-Datta** [comment]
@Tanmoy741127 The PR wasn't merged, I was wondering if you have reviewed it. Thanks !

**Comment by Tanmoy741127** [comment]
@Arkajit-Datta will check by today end . This week was too hectic. Really didn't got any time.

**Comment by Arkajit-Datta** [comment]
ohhh no worries, thanx!

**Comment by harishfalco** [comment]
Hello @tanmoysrt @Arkajit-Datta @shashankmuralidhar , 
I am still getting the `string index out of range ` errror.

code:
```
import cv2
from pyaadhaar.utils import isSecureQr
from pyaadhaar.decode import AadhaarSecureQr

qrdata = '...'
isSecureQR = (isSecureQr(qrData))
if isSecureQR:
    secure_qr = AadhaarSecureQr(int(qrData))
    decoded_secure_qr_data = secure_qr.decodeddata()
    print(decoded_secure_qr_data)
```

Screenshot

<img width="737" alt="image" src="https://github.com/tanmoysrt/pyaadhaar/assets/62054469/0808a03d-f044-43d5-9194-e4cb9ee94ebf">

**Comment by Arkajit-Datta** [comment]
Hey @harishfalco lemme have a look into the problem, there is an open PR which should solve this problem. We'll try to merge it in main Asap

**Comment by manojLondhe** [comment]
Seeing same issue `string index out of range`.
Using code changes from https://github.com/tanmoysrt/pyaadhaar/pull/10 seems to fix the error

**Comment by tanmoysrt** [comment]
@rahulc93 @manojLondhe @harishfalco  kindly update your pyaadhaar version to 2.0.2  https://pypi.org/project/pyaadhaar/ . The issues has been fixed.
Thanks @Arkajit-Datta for your valuable contribution
